# -*- coding: utf-8 -*-
"""Generate games/strat/js/data.js from worldmap.py (single source of truth)."""
import json
from pathlib import Path
from worldmap import EMPIRE_DATA, TERRITORIES

OUT = Path(__file__).resolve().parent.parent / 'games' / 'strat' / 'js' / 'data.js'

lines = ['// Generated by server/generate_client_data.py — do not edit by hand', '']
lines.append('window.EMPIRES = ' + json.dumps(EMPIRE_DATA, ensure_ascii=False, indent=2) + ';')
lines.append('')
lines.append('window.TERRITORIES = ' + json.dumps(TERRITORIES, ensure_ascii=False, indent=2) + ';')
lines.append('')
lines.append('for (const t of window.TERRITORIES) {')
lines.append('  t._px = (t.lon + 6) * 70 + 400')
lines.append('  t._py = (48 - t.lat) * 70 + 100')
lines.append('}')

OUT.write_text('\n'.join(lines), encoding='utf-8')
print(f'wrote {OUT} ({len(TERRITORIES)} territories, {len(EMPIRE_DATA)} empires)')
