/**
 * CHARACTERS.JS — Données des combattants
 * Stats, compétences, archétypes et sprites
 */
const CHARACTERS = {
    knight: {
        id: 'knight',
        name: 'Chevalier',
        role: 'Tank / Corps à corps',
        hp: 120,
        speed: 3,
        jump: 10,
        attackPower: 15,
        defense: 12,
        range: 28,
        attackSpeed: 1.0,
        critChance: 0.1,
        color: '#3498db',
        accent: '#2266cc',
        skinColor: '#f5d0a9',
        hairColor: '#1a1a1a',
        armorStyle: 'heavy',
        specialMove: 'Bouclier Sacré',
        specialDamage: 2.5,
        specialRange: 50,
        specialCost: 100,
        description: 'Encaisse les coups lourds et protège ses alliés.',
        lore: 'Gardien ancestral des royaumes perdus, le Chevalier est le dernier rempart contre les ténèbres.',
        sprite: {
            body: [[0,0,1,1,1,0,0],[0,1,1,1,1,1,0],[0,1,2,1,2,1,0],[0,1,1,1,1,1,0],[0,0,1,0,1,0,0],[0,1,1,1,1,1,0],[0,1,0,1,0,1,0]],
            idle: [0, -1, 0, 1],
            walk: [-2, -1, 2, 1],
            attack: [0, -3, 0, -1],
        },
        combos: [
            { name: 'Slash', damage: 1.0, knockback: 5, hitbox: 28 },
            { name: 'Upper Slash', damage: 1.3, knockback: 8, hitbox: 24 },
            { name: 'Shield Bash', damage: 0.8, knockback: 12, hitbox: 20 },
        ],
    },

    ranger: {
        id: 'ranger',
        name: 'Éclaireur Jungle',
        role: 'Agilité / Distance',
        hp: 90,
        speed: 5,
        jump: 12,
        attackPower: 12,
        defense: 6,
        range: 45,
        attackSpeed: 1.3,
        critChance: 0.2,
        color: '#2ecc71',
        accent: '#1a9a5a',
        skinColor: '#d4a574',
        hairColor: '#3a2200',
        armorStyle: 'light',
        specialMove: 'Pluie de Flèches',
        specialDamage: 1.8,
        specialRange: 80,
        specialCost: 100,
        description: 'Rapide et mortel au milieu de la végétation dense.',
        lore: 'Né dans la canopée, l\'Éclaireur se déplace comme le vent et frappe comme la pluie.',
        sprite: {
            body: [[0,0,1,1,1,0,0],[0,1,1,1,1,1,0],[0,1,2,1,2,1,0],[0,0,1,1,1,0,0],[0,0,1,0,1,0,0],[0,1,1,1,1,1,0],[0,1,0,1,0,1,0]],
            idle: [0, -1, 0, 1],
            walk: [-3, -1, 3, 1],
            attack: [0, -2, 0, 0],
        },
        combos: [
            { name: 'Quick Strike', damage: 0.8, knockback: 3, hitbox: 35 },
            { name: 'Arrow Shot', damage: 1.2, knockback: 6, hitbox: 45 },
            { name: 'Vine Whip', damage: 1.0, knockback: 8, hitbox: 40 },
        ],
    },

    berserker: {
        id: 'berserker',
        name: 'Guerrier du Désert',
        role: 'Force / Rage',
        hp: 100,
        speed: 4,
        jump: 9,
        attackPower: 18,
        defense: 8,
        range: 30,
        attackSpeed: 0.7,
        critChance: 0.15,
        color: '#e74c3c',
        accent: '#c0392b',
        skinColor: '#c08060',
        hairColor: '#8a1a1a',
        armorStyle: 'medium',
        specialMove: 'Frappe Sismique',
        specialDamage: 3.0,
        specialRange: 60,
        specialCost: 100,
        description: 'Dégâts dévastateurs, idéal pour briser les carapaces.',
        lore: 'Forgé dans les sables brûlants, sa rage est aussi infinie que le désert lui-même.',
        sprite: {
            body: [[0,1,1,1,1,1,0],[1,1,1,1,1,1,1],[1,1,2,1,2,1,1],[1,1,1,1,1,1,1],[0,1,1,0,1,1,0],[0,1,1,1,1,1,0],[0,1,0,1,0,1,0]],
            idle: [0, -1, 0, 1],
            walk: [-2, -1, 2, 1],
            attack: [0, -4, 0, -2],
        },
        combos: [
            { name: 'Axe Swing', damage: 1.2, knockback: 7, hitbox: 30 },
            { name: 'Ground Pound', damage: 1.5, knockback: 10, hitbox: 35 },
            { name: 'Rage Slash', damage: 2.0, knockback: 14, hitbox: 28 },
        ],
    },

    mage: {
        id: 'mage',
        name: 'Mage Élémentaire',
        role: 'Support / Contrôle',
        hp: 80,
        speed: 3.5,
        jump: 10,
        attackPower: 20,
        defense: 5,
        range: 55,
        attackSpeed: 0.9,
        critChance: 0.25,
        color: '#9b59b6',
        accent: '#7d3c98',
        skinColor: '#f0d0b0',
        hairColor: '#4a2a6a',
        armorStyle: 'robes',
        specialMove: 'Nova de Glace',
        specialDamage: 2.8,
        specialRange: 100,
        specialCost: 100,
        description: 'Contrôle le terrain et gele les ennemis à distance.',
        lore: 'Maître des éléments, il invoque les forces de la nature pour écraser ses ennemis.',
        sprite: {
            body: [[0,0,1,1,1,0,0],[0,1,1,1,1,1,0],[0,1,2,1,2,1,0],[0,1,1,1,1,1,0],[0,0,1,0,1,0,0],[0,1,1,1,1,1,0],[0,1,0,1,0,1,0]],
            idle: [0, -1, 0, 1],
            walk: [-1, -1, 1, 1],
            attack: [0, -2, 0, 0],
        },
        combos: [
            { name: 'Fireball', damage: 1.3, knockback: 4, hitbox: 55 },
            { name: 'Ice Shard', damage: 1.0, knockback: 6, hitbox: 50 },
            { name: 'Lightning Bolt', damage: 1.8, knockback: 8, hitbox: 60 },
        ],
    },

    ninja: {
        id: 'ninja',
        name: 'Ninja',
        role: 'Assassin / Furtif',
        hp: 75,
        speed: 5.5,
        jump: 13,
        attackPower: 14,
        defense: 4,
        range: 22,
        attackSpeed: 1.5,
        critChance: 0.3,
        color: '#2c3e50',
        accent: '#e74c3c',
        skinColor: '#e8c8a0',
        hairColor: '#1a1a1a',
        armorStyle: 'ninja',
        specialMove: 'Shadow Strike',
        specialDamage: 3.5,
        specialRange: 40,
        specialCost: 100,
        description: 'Frappe dans l\'ombre, invisible et mortel.',
        lore: 'Maître de l\'art du ninjutsu, il strike avant même que l\'ennemi ne le voie.',
        sprite: {
            body: [[0,0,1,1,1,0,0],[0,1,1,1,1,1,0],[0,1,2,1,2,1,0],[0,0,1,1,1,0,0],[0,0,1,0,1,0,0],[0,1,1,1,1,1,0],[0,1,0,1,0,1,0]],
            idle: [0, -1, 0, 1],
            walk: [-3, -1, 3, 1],
            attack: [0, -2, 0, 0],
        },
        combos: [
            { name: 'Shuriken', damage: 0.7, knockback: 2, hitbox: 30 },
            { name: 'Dash Slash', damage: 1.4, knockback: 5, hitbox: 25 },
            { name: 'Backstab', damage: 2.2, knockback: 8, hitbox: 20 },
        ],
    },

    paladin: {
        id: 'paladin',
        name: 'Paladin',
        role: 'Tank / Soutien',
        hp: 130,
        speed: 2.8,
        jump: 8,
        attackPower: 12,
        defense: 15,
        range: 32,
        attackSpeed: 0.8,
        critChance: 0.05,
        color: '#f1c40f',
        accent: '#d4ac0d',
        skinColor: '#f5d0a9',
        hairColor: '#ffcc00',
        armorStyle: 'plate',
        specialMove: 'Holy Light',
        specialDamage: 2.0,
        specialRange: 70,
        specialCost: 100,
        description: 'Protecteur sacré, guérit et shield ses alliés.',
        lore: 'Chevalier de la lumière divine, il protège les faibles et châtie les méchants.',
        sprite: {
            body: [[0,1,1,1,1,1,0],[1,1,1,1,1,1,1],[1,1,2,1,2,1,1],[1,1,1,1,1,1,1],[1,1,1,0,1,1,1],[0,1,1,1,1,1,0],[0,1,0,1,0,1,0]],
            idle: [0, -1, 0, 1],
            walk: [-1, -1, 1, 1],
            attack: [0, -3, 0, -1],
        },
        combos: [
            { name: 'Mace Swing', damage: 0.9, knockback: 6, hitbox: 32 },
            { name: 'Shield Charge', damage: 1.1, knockback: 12, hitbox: 28 },
            { name: 'Holy Smite', damage: 1.6, knockback: 8, hitbox: 35 },
        ],
    },

    archer: {
        id: 'archer',
        name: 'Archer',
        role: 'Distance / Précision',
        hp: 85,
        speed: 4.0,
        jump: 11,
        attackPower: 11,
        defense: 5,
        range: 60,
        attackSpeed: 1.2,
        critChance: 0.25,
        color: '#27ae60',
        accent: '#1e8449',
        skinColor: '#d4a574',
        hairColor: '#5a3a1a',
        armorStyle: 'leather',
        specialMove: 'Rain of Arrows',
        specialDamage: 1.5,
        specialRange: 120,
        specialCost: 100,
        description: 'Maître du arc, jamais ne rate sa cible.',
        lore: 'Chasseur des bois, chaque flèche porte la précision de la nature.',
        sprite: {
            body: [[0,0,1,1,1,0,0],[0,1,1,1,1,1,0],[0,1,2,1,2,1,0],[0,1,1,1,1,1,0],[0,0,1,0,1,0,0],[0,1,1,1,1,1,0],[0,1,0,1,0,1,0]],
            idle: [0, -1, 0, 1],
            walk: [-2, -1, 2, 1],
            attack: [0, -2, 0, 0],
        },
        combos: [
            { name: 'Arrow', damage: 0.9, knockback: 3, hitbox: 60 },
            { name: 'Power Shot', damage: 1.5, knockback: 7, hitbox: 55 },
            { name: 'Multi Shot', damage: 0.6, knockback: 2, hitbox: 65 },
        ],
    },

    warlock: {
        id: 'warlock',
        name: 'Warlock',
        role: 'Dégâts / DoT',
        hp: 70,
        speed: 3.2,
        jump: 9,
        attackPower: 22,
        defense: 3,
        range: 50,
        attackSpeed: 0.8,
        critChance: 0.2,
        color: '#8e44ad',
        accent: '#6c3483',
        skinColor: '#c8a888',
        hairColor: '#2a1a3a',
        armorStyle: 'dark',
        specialMove: 'Void Explosion',
        specialDamage: 3.2,
        specialRange: 80,
        specialCost: 100,
        description: 'Invoque les ténèbres pour dévorer ses ennemis.',
        lore: 'Chasseur d\'âmes, il puise son pouvoir dans les abysses du néant.',
        sprite: {
            body: [[0,0,1,1,1,0,0],[0,1,1,1,1,1,0],[0,1,2,1,2,1,0],[0,1,1,1,1,1,0],[0,0,1,0,1,0,0],[0,1,1,1,1,1,0],[0,1,0,1,0,1,0]],
            idle: [0, -1, 0, 1],
            walk: [-1, -1, 1, 1],
            attack: [0, -2, 0, 0],
        },
        combos: [
            { name: 'Shadow Bolt', damage: 1.4, knockback: 3, hitbox: 50 },
            { name: 'Drain Life', damage: 1.0, knockback: 2, hitbox: 45 },
            { name: 'Dark Nova', damage: 2.0, knockback: 10, hitbox: 55 },
        ],
    },
};

// Stats de base normalisées
const BASE_STATS = {
    hp: { min: 60, max: 150 },
    speed: { min: 2, max: 6 },
    jump: { min: 7, max: 14 },
    attackPower: { min: 8, max: 25 },
    defense: { min: 2, max: 18 },
    range: { min: 18, max: 70 },
    attackSpeed: { min: 0.5, max: 1.8 },
    critChance: { min: 0.05, max: 0.35 },
};

// Raretés
const RARITIES = {
    common: { name: 'Commun', color: '#aaaaaa', statBonus: 0 },
    uncommon: { name: 'Peu Commun', color: '#44cc44', statBonus: 0.1 },
    rare: { name: 'Rare', color: '#4488ff', statBonus: 0.2 },
    epic: { name: 'Épique', color: '#aa44ff', statBonus: 0.35 },
    legendary: { name: 'Légendaire', color: '#ffaa00', statBonus: 0.5 },
};

// Listes d'unlockables
const UNLOCKABLES = {
    skins: [
        { id: 'default', name: 'Classique', requirement: null },
        { id: 'golden', name: 'Doré', requirement: 'wins_10' },
        { id: 'shadow', name: 'Ombre', requirement: 'kills_100' },
        { id: 'elemental', name: 'Élémentaire', requirement: 'combo_10' },
        { id: 'neon', name: 'Néon', requirement: 'perfect' },
    ],
    titles: [
        { id: 'novice', name: 'Novice', requirement: null },
        { id: 'warrior', name: 'Guerrier', requirement: 'wins_5' },
        { id: 'champion', name: 'Champion', requirement: 'wins_20' },
        { id: 'legend', name: 'Légende', requirement: 'wins_50' },
        { id: 'god', name: 'Dieu du Combat', requirement: 'wins_100' },
    ],
    effects: [
        { id: 'none', name: 'Aucun', requirement: null },
        { id: 'fire', name: 'Feu', requirement: 'kills_50' },
        { id: 'ice', name: 'Glace', requirement: 'kills_100' },
        { id: 'lightning', name: 'Foudre', requirement: 'kills_200' },
        { id: 'void', name: 'Néant', requirement: 'kills_500' },
    ],
};

// Export pour utilisation
if (typeof window !== 'undefined') {
    window.CHARACTERS = CHARACTERS;
    window.BASE_STATS = BASE_STATS;
    window.RARITIES = RARITIES;
    window.UNLOCKABLES = UNLOCKABLES;
}
